name: Build Hello World App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # =====================
      # Build .NET API
      # =====================

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore API
        run: dotnet restore backend/HelloApi

      - name: Publish API
        run: dotnet publish backend/HelloApi -c Release -o publish

      - name: Upload API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-api
          path: publish

      # =====================
      # Build Angular UI
      # =====================

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install UI Packages
        run: |
          cd frontend/hello-ui
          npm install

      - name: Build Angular
        run: |
          cd frontend/hello-ui
          npm run build

      - name: Upload UI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-ui
          path: frontend/hello-ui/dist