name: Build Hello World App

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore API
        run: dotnet restore backend/HelloApi

      - name: Publish API
        run: dotnet publish backend/HelloApi -c Release -o publish

      - name: Upload API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-api
          path: publish

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install UI Packages
        run: |
          cd frontend/hello-ui
          npm install

      - name: Build Angular
        run: |
          cd frontend/hello-ui
          npm run build

      - name: Upload UI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-ui
          path: frontend/hello-ui/dist

  deploy:
    needs: build

    runs-on: self-hosted

    steps:
      - name: Download API Artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-api
          path: /Users/hemanthpeddi/Downloads/deployments/helloapi

      - name: Stop Existing App
        run: pkill dotnet || true

      - name: Start App
        run: |
          cd /Users/hemanthpeddi/Downloads/deployments/helloapi
          nohup dotnet HelloApi.dll > app.log 2>&1 &
      - name: Start App
        run: |
          cd /Users/hemanthpeddi/Downloads/deployments/helloapi
          pkill dotnet || true
          nohup dotnet HelloApi.dll --urls=http://localhost:5000 > app.log 2>&1 &
          sleep 5
          ps -ef | grep dotnet
          cat app.log